/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telaprincipal;

import escalonador.processos.ProcessarArquivo;
import ajustes.AjustarJanelas;
/**
 *
 * @author aliss
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        
        initComponents();
        this.setTitle("Escalonador de Processos");
        this.setResizable(false);
        this.setSize(800, 450);
        this.setLocationRelativeTo(null);      
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_principal = new javax.swing.JPanel();
        lbl_escalonador = new javax.swing.JLabel();
        lbl_trabalho_so = new javax.swing.JLabel();
        pnl_integrantes = new javax.swing.JPanel();
        lbl_integrantes = new javax.swing.JLabel();
        lbl_alisson = new javax.swing.JLabel();
        lbl_lucas = new javax.swing.JLabel();
        lbl_fellippe = new javax.swing.JLabel();
        btn_escolher_arquivo = new javax.swing.JButton();
        lbl_processo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escalonador de Processos");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(getPreferredSize());
        setMinimumSize(getPreferredSize());
        setName("TelaInicial"); // NOI18N
        setPreferredSize(getPreferredSize());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_principal.setBackground(new java.awt.Color(255, 255, 255));
        pnl_principal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnl_principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_escalonador.setFont(new java.awt.Font("Georgia", 1, 40)); // NOI18N
        lbl_escalonador.setText("Escalonador de Processos");
        pnl_principal.add(lbl_escalonador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 550, 40));

        lbl_trabalho_so.setText("Trabalho de Sistemas Operacionais");
        pnl_principal.add(lbl_trabalho_so, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));

        pnl_integrantes.setBackground(new java.awt.Color(249, 249, 249));

        lbl_integrantes.setText("INTEGRANTES:");

        lbl_alisson.setText("-Alisson Weiss");

        lbl_lucas.setText("-Lucas Siqueira");

        lbl_fellippe.setText("-Luiz Fellippe");

        javax.swing.GroupLayout pnl_integrantesLayout = new javax.swing.GroupLayout(pnl_integrantes);
        pnl_integrantes.setLayout(pnl_integrantesLayout);
        pnl_integrantesLayout.setHorizontalGroup(
            pnl_integrantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_integrantesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnl_integrantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_fellippe)
                    .addComponent(lbl_lucas)
                    .addComponent(lbl_alisson)
                    .addComponent(lbl_integrantes))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        pnl_integrantesLayout.setVerticalGroup(
            pnl_integrantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_integrantesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_integrantes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_alisson)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_lucas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_fellippe)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_principal.add(pnl_integrantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        btn_escolher_arquivo.setText("Selecionar");
        btn_escolher_arquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_escolher_arquivoActionPerformed(evt);
            }
        });
        pnl_principal.add(btn_escolher_arquivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, -1, -1));

        lbl_processo.setText("Selecione o arquivo de processos");
        pnl_principal.add(lbl_processo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, -1, -1));

        getContentPane().add(pnl_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 13, 780, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_escolher_arquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_escolher_arquivoActionPerformed
        ProcessarArquivo arq = new ProcessarArquivo();
        arq.escolherArquivo();
        
        if (arq.getAbriu()){
        
            TelaPrincipal tela = new TelaPrincipal();
            dispose();
            tela.setVisible(true);
        }
        
    }//GEN-LAST:event_btn_escolher_arquivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_escolher_arquivo;
    private javax.swing.JLabel lbl_alisson;
    private javax.swing.JLabel lbl_escalonador;
    private javax.swing.JLabel lbl_fellippe;
    private javax.swing.JLabel lbl_integrantes;
    private javax.swing.JLabel lbl_lucas;
    private javax.swing.JLabel lbl_processo;
    private javax.swing.JLabel lbl_trabalho_so;
    private javax.swing.JPanel pnl_integrantes;
    private javax.swing.JPanel pnl_principal;
    // End of variables declaration//GEN-END:variables
}
